import { vi } from 'vitest';
import type { AppEditorWorkspaceProps } from './AppEditorWorkspaceTypes';
import type { AppEditorUiState } from '../utils/appEditorUiState';

export const appEditorWorkspaceUiState: AppEditorUiState = {
  hasSourceContent: true,
  hasPreviewContent: true,
  isPreviewSameAsSource: false,
  isSourceJsonCandidate: true,
  sourceStandaloneDeepFormatKind: null,
  canUseAutoSave: true,
  isAutoSaveActive: false,
  autoSaveTitle: '自动保存',
  autoSaveAriaLabel: '自动保存',
  copySourceTitle: '复制 SOURCE',
  clearSourceTitle: '清空 SOURCE',
  sourceAiRepairTitle: '使用 AI 修复 SOURCE JSON',
  transformReportTitle: '深度解析报告',
  applyPreviewTitle: '应用 PREVIEW',
  copyPreviewTitle: '复制 PREVIEW',
  clearSourceConfirmMessage: '',
  pasteSourceConfirmMessage: '',
  applyPreviewConfirmMessage: '',
  applySchemaExampleConfirmMessage: '',
  schemeInspectConfirmMessage: '',
};

export const buildAppEditorWorkspaceProps = (
  overrides: Partial<AppEditorWorkspaceProps> = {}
): AppEditorWorkspaceProps => ({
  input: '{"a":1}',
  output: '{\n  "a": 1\n}',
  activeFile: null,
  activeFileId: null,
  files: [],
  activeEditor: 'SOURCE',
  leftPaneWidthPercent: 50,
  isPaneResizing: false,
  isProcessing: false,
  isOutputTransforming: false,
  aiRepairSummary: null,
  sourceValidation: { isValid: true },
  previewValidation: { isValid: true },
  sourceErrorLocation: null,
  previewErrorLocation: null,
  sourceErrorLocateSignal: 0,
  jsonSchemaWarning: '',
  jsonSchemaDiagnosticHighlights: [],
  deepFormatWarning: undefined,
  deepFormatInfo: undefined,
  hasTransformReportContext: false,
  highlightRange: null,
  editorUiState: appEditorWorkspaceUiState,
  onInputChange: vi.fn(),
  onOutputChange: vi.fn(),
  onSourceFocus: vi.fn(),
  onPreviewFocus: vi.fn(),
  onCursorPositionChange: vi.fn(),
  onTabClick: vi.fn(),
  onCloseFile: vi.fn(),
  onNewTab: vi.fn(),
  onSaveViewState: vi.fn(),
  onSourceAiFix: vi.fn(),
  onPasteSource: vi.fn(),
  onCopySource: vi.fn(),
  onClearSource: vi.fn(),
  onToggleAutoSave: vi.fn(),
  onOpenTransformReport: vi.fn(),
  onApplyPreviewToSource: vi.fn(),
  onCopyPreview: vi.fn(),
  onSchemeEdit: vi.fn(),
  onPaneResizeMouseDown: vi.fn(),
  onPaneResizeKeyDown: vi.fn(),
  onCloseAiRepairSummary: vi.fn(),
  onCopyAiRepairSummarySuccess: vi.fn(),
  onCopyAiRepairSummaryError: vi.fn(),
  ...overrides,
});
