import type { AppPreviewEditorPaneProps } from './AppPreviewEditorPane';
import type { AppSourceEditorPaneProps } from './AppSourceEditorPane';
import type { AppEditorWorkspaceProps } from './AppEditorWorkspaceTypes';

type CursorPositionHandler = (line: number, column: number) => void;

export const buildAppEditorWorkspaceSourcePaneProps = (
  {
    input,
    activeFile,
    activeFileId,
    files,
    leftPaneWidthPercent,
    isProcessing,
    sourceValidation,
    sourceErrorLocation,
    sourceErrorLocateSignal,
    jsonSchemaWarning,
    jsonSchemaDiagnosticHighlights,
    editorUiState,
    onSourceEditorMount,
    onInputChange,
    onSourceFocus,
    onTabClick,
    onCloseFile,
    onNewTab,
    onSourceAiFix,
    onPasteSource,
    onCopySource,
    onClearSource,
    onToggleAutoSave,
  }: AppEditorWorkspaceProps,
  onCursorPositionChange: CursorPositionHandler
): AppSourceEditorPaneProps => ({
  input,
  activeFile,
  activeFileId,
  files,
  leftPaneWidthPercent,
  isProcessing,
  sourceValidation,
  sourceErrorLocation,
  sourceErrorLocateSignal,
  jsonSchemaWarning,
  jsonSchemaDiagnosticHighlights,
  editorUiState,
  onSourceEditorMount,
  onInputChange,
  onSourceFocus,
  onCursorPositionChange,
  onTabClick,
  onCloseFile,
  onNewTab,
  onSourceAiFix,
  onPasteSource,
  onCopySource,
  onClearSource,
  onToggleAutoSave,
});

export const buildAppEditorWorkspacePreviewPaneProps = (
  {
    output,
    activeFileId,
    isOutputTransforming,
    previewValidation,
    previewErrorLocation,
    deepFormatWarning,
    deepFormatInfo,
    hasTransformReportContext,
    schemeDisplayHeaderMarkers,
    highlightRange,
    editorUiState,
    isScrollSyncEnabled,
    onPreviewEditorMount,
    onOutputChange,
    onPreviewFocus,
    onOpenTransformReport,
    onApplyPreviewToSource,
    onCopyPreview,
    onToggleScrollSync,
    onSchemeEdit,
  }: AppEditorWorkspaceProps,
  onCursorPositionChange: CursorPositionHandler
): AppPreviewEditorPaneProps => ({
  output,
  activeFileId,
  isOutputTransforming,
  previewValidation,
  previewErrorLocation,
  deepFormatWarning,
  deepFormatInfo,
  hasTransformReportContext,
  schemeDisplayHeaderMarkers,
  highlightRange,
  editorUiState,
  isScrollSyncEnabled,
  onPreviewEditorMount,
  onOutputChange,
  onPreviewFocus,
  onCursorPositionChange,
  onOpenTransformReport,
  onApplyPreviewToSource,
  onCopyPreview,
  onToggleScrollSync,
  onSchemeEdit,
});
