import {
  DEPLOY_SHELL_SYNTAX_REFERENCES,
  AI_EVOLUTION_LOOP_REFERENCES,
  AI_SAFETY_BOUNDARY_REFERENCES,
  CHUNK_LOAD_RECOVERY_CATCH_REFERENCES,
  PUBLIC_FRONTEND_ASSET_AUDIT_REFERENCES,
  SUBAGENT_DELEGATION_REFERENCES,
  VERSION_CHANGELOG_REFERENCES,
} from './aiGovernanceReferenceGroups.mjs';

export const CORE_ENTRY_REFERENCES = [
  'rules/code-style.md',
  'docs/AI-ENGINEERING-PLAYBOOK.md',
  'docs/AI-ASSET-REGISTRY.md',
  'node scripts/ci/check-ai-governance.mjs',
];

export const ENTRY_GOVERNANCE_REFERENCES = [
  ...SUBAGENT_DELEGATION_REFERENCES,
  ...AI_EVOLUTION_LOOP_REFERENCES,
  ...VERSION_CHANGELOG_REFERENCES,
];

export const CODE_STYLE_GOVERNANCE_REFERENCES = [
  ...AI_EVOLUTION_LOOP_REFERENCES,
  ...VERSION_CHANGELOG_REFERENCES,
];

export const RUNTIME_GOVERNANCE_REFERENCES = [
  ...SUBAGENT_DELEGATION_REFERENCES,
  ...DEPLOY_SHELL_SYNTAX_REFERENCES,
  ...CHUNK_LOAD_RECOVERY_CATCH_REFERENCES,
  ...AI_SAFETY_BOUNDARY_REFERENCES,
  ...AI_EVOLUTION_LOOP_REFERENCES,
  ...VERSION_CHANGELOG_REFERENCES,
  'node scripts/ci/check-frontend-static-retention.mjs',
  ...PUBLIC_FRONTEND_ASSET_AUDIT_REFERENCES,
];
