import { AI_GOVERNANCE_CUSTOM_AI_ENTRIES } from './aiGovernanceDiscoveryEntries.mjs';

export const AI_TOOLS_SETUP_REFERENCES = [
  'AGENTS.md',
  'CLAUDE.md',
  '.claude/README.md',
  '.codex/README.md',
  'docs/AI-ASSET-REGISTRY.md',
  'docs/AI-GOVERNANCE-DECISIONS.md',
  '.cursorrules',
  ...AI_GOVERNANCE_CUSTOM_AI_ENTRIES,
  'MCP 配置',
  '.codex/config.toml',
  'trusted project',
  '新建任务',
  '兼容/可分发包',
  '.agents/plugins/marketplace.json',
  'plugins/',
  'source of truth',
  'docs/AI-CONFIG-INTEGRATION.md',
  'docs/AI-ENGINEERING-PLAYBOOK.md',
  'docs/AI-EVOLUTION-PLAYBOOK.md',
  '.agents/skills/jsonutils-ai-infra-evolver/SKILL.md',
  'node scripts/ci/check-ai-governance.mjs',
  'node scripts/ci/check-ai-evolution-evals.mjs',
  '--json',
];
