import {
  DEPLOY_SHELL_SYNTAX_REFERENCES,
  CHUNK_LOAD_RECOVERY_CATCH_REFERENCES,
  PUBLIC_FRONTEND_ASSET_AUDIT_REFERENCES,
  VERSION_CHANGELOG_REFERENCES,
} from './aiGovernanceReleaseReferenceGroups.mjs';
import { SUBAGENT_DELEGATION_REFERENCES } from './aiGovernanceDelegationReferenceGroup.mjs';
import { AI_EVOLUTION_LOOP_REFERENCES } from './aiGovernanceEvolutionReferenceGroup.mjs';
import { AI_SAFETY_BOUNDARY_REFERENCES } from './aiGovernanceSafetyReferenceGroup.mjs';
import { PROJECT_AI_ASSET_OWNERSHIP_REFERENCES } from './aiGovernanceEntryCoreReferenceGroups.mjs';

export const CORE_SKILL_GOVERNANCE_REFERENCES = [
  ...SUBAGENT_DELEGATION_REFERENCES,
  ...AI_SAFETY_BOUNDARY_REFERENCES,
  ...VERSION_CHANGELOG_REFERENCES,
];

export const SPECIALIZED_SKILL_GOVERNANCE_REFERENCES = [
  ...CORE_SKILL_GOVERNANCE_REFERENCES,
  ...PROJECT_AI_ASSET_OWNERSHIP_REFERENCES,
  ...AI_EVOLUTION_LOOP_REFERENCES,
  'scripts/ci/run-ai-evolution-cases.mjs',
];

export const RUNTIME_GOVERNANCE_REFERENCES = [
  ...PROJECT_AI_ASSET_OWNERSHIP_REFERENCES,
  ...SUBAGENT_DELEGATION_REFERENCES,
  ...DEPLOY_SHELL_SYNTAX_REFERENCES,
  ...CHUNK_LOAD_RECOVERY_CATCH_REFERENCES,
  ...AI_SAFETY_BOUNDARY_REFERENCES,
  ...AI_EVOLUTION_LOOP_REFERENCES,
  ...VERSION_CHANGELOG_REFERENCES,
  'node scripts/ci/check-frontend-static-retention.mjs',
  ...PUBLIC_FRONTEND_ASSET_AUDIT_REFERENCES,
];
