import { AI_GOVERNANCE_REFERENCE_DOCS_MISSING_CASES } from './aiGovernanceReferenceDocsMissingCases.mjs';
import { AI_GOVERNANCE_REFERENCE_PULL_REQUEST_MISSING_CASES } from './aiGovernanceReferencePullRequestMissingCases.mjs';
import { AI_GOVERNANCE_REFERENCE_TOOL_ENTRY_MISSING_CASES } from './aiGovernanceReferenceToolEntryMissingCases.mjs';

export const AI_GOVERNANCE_REFERENCE_ENTRY_MISSING_CASES = [
  ...AI_GOVERNANCE_REFERENCE_TOOL_ENTRY_MISSING_CASES,
  ...AI_GOVERNANCE_REFERENCE_PULL_REQUEST_MISSING_CASES,
  ...AI_GOVERNANCE_REFERENCE_DOCS_MISSING_CASES,
];
