export const AI_GOVERNANCE_CHECKS_SHARED_REFERENCE_FIXTURE = [
  'AGENTS.md',
  'CLAUDE.md',
  '.claude/ai-tools-guide.md',
  '.claude/README.md',
  '.cursorrules',
  '.comate/rules/code-style.md',
  '.codex/README.md',
  '.agents/plugins/marketplace.json',
  'plugins/',
  'source of truth',
  '.github/copilot-instructions.md',
  'rules/code-style.md',
  'docs/AI-ENGINEERING-PLAYBOOK.md',
  'docs/AI-EVOLUTION-PLAYBOOK.md',
  'docs/AI-GOVERNANCE-DECISIONS.md',
  'docs/AI-CONFIG-INTEGRATION.md',
  'docs/AI-TOOLS-SETUP.md',
  'docs/AI-ASSET-REGISTRY.md',
  '.agents/skills/jsonutils-maintainer/SKILL.md',
  '.agents/skills/jsonutils-ai-infra-evolver/SKILL.md',
  'skills/jsonutils-maintainer/SKILL.md',
  '.github/PULL_REQUEST_TEMPLATE.md',
  '.claude/settings.local.json',
  'git status --short --branch',
  'npm run lint',
  'npm run typecheck',
  'npm run build',
  'npm run check:preloads',
  'node scripts/ci/check-deploy-shell-syntax.mjs',
  'node scripts/ci/check-chunk-load-recovery-catches.mjs',
  'dispatchChunkLoadRecoveryEvent',
  '手动懒加载',
  'REMOTE_SCRIPT heredoc',
  'workflow run',
  'node scripts/ci/check-frontend-static-retention.mjs',
  'node scripts/ci/check-production-frontend-assets.mjs',
  'node scripts/ci/check-maintainability-budgets.mjs',
  'node scripts/ci/check-ai-governance.mjs',
  'node scripts/ci/check-ai-evolution-evals.mjs',
  'node scripts/ci/check-ai-asset-distribution.mjs --workspace',
  'node scripts/ci/check-ai-asset-distribution.mjs --index',
  '使用 `--head`',
  'CI 用 `--head`',
  '不会因 clone 或打开项目自动安装',
  'node scripts/ci/manage-project-plugins.mjs --check',
  '新建任务',
  'scripts/ci/run-ai-evolution-cases.mjs',
  '--json',
  'scripts/ci/aiGovernanceAssetRegistryEvidence.mjs',
  'referenceRules.file',
  'node scripts/ci/check-version-consistency.mjs',
  'frontend/package.json',
  'frontend/package-lock.json',
  'CHANGELOG.md',
  'jsonutils-maintainer 0.1.0',
  'jsonutils-ai-infra-evolver 0.1.0',
  'node scripts/ci/check-ai-validation-whitespace.mjs',
  'Content-Type',
  'fallback 成 HTML',
  'CSS `url(...)`',
  'CSS `@import`',
  '--extra-asset',
  '子 Agent 委派',
  '主线程负责',
  '拆分边界',
  '读写范围',
  '排除项',
  '期望输出',
  '未覆盖风险',
  '收窄',
  '任务：',
  '结论：',
  '证据：',
  '修改文件：',
  '验证：',
  '未覆盖：',
  '下一步建议：',
  '本地规则优先',
  '用户手动触发',
  '敏感内容不外泄',
  '可验证闭环',
  '测试',
  '脚本',
  '可复核日志',
  '复盘沉淀',
  '触发条件',
  '反例',
  '验证方式',
  '适用边界',
  '规则/skill 回写',
  '决策记录',
  '回写追踪',
  '负向测试',
  '锁定测试',
  '治理校验',
  '本机私有配置',
  '显式豁免',
  'MCP 配置',
  '可维护性预算',
  '.mcp.json',
  'scripts/mcp/jsonutils-governance-server.mjs',
  'jsonutils-governance',
  '.cursor/mcp.json',
  '.cursor/rules',
  '.vscode/mcp.json',
  '.github/copilot-instructions.md',
  'Copilot 根入口',
  '.github/instructions',
  '.github/prompts',
  '.github/agents',
  '.github/chatmodes',
].join('\n');
