import { AI_GOVERNANCE_REQUIRED_MCP_RUNTIME_FILES } from './aiGovernanceRequiredMcpRuntimeFiles.mjs';

export const AI_GOVERNANCE_MCP_FILES = [
  '.mcp.json',
  '.codex/config.toml',
  'scripts/ci/aiGovernanceCodexProjectMcpConfig.mjs',
  'scripts/ci/aiGovernanceCodexProjectMcpConfig.test.mjs',
  'scripts/ci/aiGovernanceRequiredMcpRuntimeFiles.mjs',
  ...AI_GOVERNANCE_REQUIRED_MCP_RUNTIME_FILES,
  'scripts/mcp/jsonutils-governance-report-tool.mjs',
  'scripts/mcp/jsonutils-governance-scorecard-tool.mjs',
  'scripts/mcp/jsonutils-governance-assets.mjs',
  'scripts/mcp/jsonutils-governance-evaluations.mjs',
  'scripts/mcp/jsonutils-governance-evaluation-projection.mjs',
  'scripts/mcp/jsonutils-governance-evaluation-outcomes.mjs',
  'scripts/mcp/jsonutils-governance-resources.mjs',
  'scripts/mcp/jsonutils-governance-context.mjs',
  'scripts/mcp/jsonutils-governance-context-builder.mjs',
  'scripts/mcp/jsonutils-governance-decisions.mjs',
  'scripts/mcp/jsonutils-governance-project-summary.mjs',
  'scripts/mcp/jsonutils-governance-report-summary.mjs',
  'scripts/mcp/jsonutils-governance-handoff.mjs',
  'scripts/mcp/jsonutils-governance-validation-plan.mjs',
  'scripts/mcp/jsonutils-governance-validation-rules.mjs',
  'scripts/mcp/jsonutils-governance-worktree.mjs',
];
