import { AI_GOVERNANCE_CI_COMMAND_FILES } from './aiGovernanceCiCommandDescriptors.mjs';
import { AI_GOVERNANCE_MCP_FILES } from './aiGovernanceRequiredMcpFiles.mjs';
import { AI_GOVERNANCE_REQUIRED_VALIDATION_FILES } from './aiGovernanceRequiredValidationFiles.mjs';

export const AI_GOVERNANCE_CHECK_FILES = [
  'scripts/ci/aiGovernanceAssetDistribution.mjs',
  'scripts/ci/aiGovernanceAssetDistribution.test.mjs',
  'scripts/ci/aiGovernanceAssetDistributionDiscovery.test.mjs',
  'scripts/ci/aiGovernanceAssetDistributionFiles.mjs',
  'scripts/ci/aiGovernanceAssetDistributionFiles.test.mjs',
  'scripts/ci/aiGovernanceAssetDistributionGitEvidence.mjs',
  'scripts/ci/aiGovernanceAssetDistributionReadiness.mjs',
  'scripts/ci/aiGovernanceAssetDistributionReadiness.test.mjs',
  'scripts/ci/aiGovernanceAssetDistributionRedteam.test.mjs',
  'scripts/ci/aiGovernanceMaturityScorecardDistribution.mjs',
  'scripts/ci/aiGovernanceMaturityScorecardDistribution.test.mjs',
  'scripts/ci/aiGovernanceImplementationFiles.mjs',
  'scripts/ci/aiGovernanceImplementationFiles.test.mjs',
  'scripts/ci/aiGovernanceClaudeSkillAdapters.mjs',
  'scripts/ci/aiGovernanceClaudeSkillAdapters.test.mjs',
  'scripts/ci/aiGovernanceClaudeSkillAdapterCaseDescriptors.mjs',
  'scripts/ci/aiGovernanceChecksUnit.test.mjs',
  'scripts/ci/aiGovernanceCiContract.test.mjs',
  'scripts/ci/aiGovernanceProjectCliArgs.test.mjs',
  'scripts/ci/aiGovernanceSkillYamlAuthority.mjs',
  'scripts/ci/aiGovernanceSkillIdentityContract.mjs',
  'scripts/ci/aiGovernanceSkillOptionalFieldsContract.mjs',
  'scripts/ci/aiGovernanceSkillOptionalFieldsContract.test.mjs',
  'scripts/ci/aiGovernanceSkillYamlAmbiguity.test.mjs',
  'scripts/ci/aiGovernanceSkillUiYamlAmbiguity.test.mjs',
  'scripts/ci/aiGovernanceSkillSourceTextContract.test.mjs',
  'scripts/ci/check-deploy-shell-syntax.mjs',
  'scripts/ci/check-frontend-static-retention.mjs',
  'scripts/ci/check-production-frontend-assets.mjs',
  'scripts/ci/check-chunk-load-recovery-catches.mjs',
  ...AI_GOVERNANCE_MCP_FILES,
  ...AI_GOVERNANCE_REQUIRED_VALIDATION_FILES,
  ...AI_GOVERNANCE_CI_COMMAND_FILES,
];
