import { AI_EVOLUTION_CODEX_CASES } from './aiGovernanceEvolutionCodexCaseDescriptors.mjs';
import { deliveryBlockedCommand } from './aiGovernanceEvolutionCaseFailure.mjs';

const nodeTest = (...files) => ['--test', ...files];

export const AI_EVOLUTION_EXECUTABLE_CASES = Object.freeze({
  'rule-project-ai-asset-ownership': {
    caseVersion: 7,
    subjectVersion: '2026-07-14.3',
    evidenceScope: 'deterministic-case',
    evidence: ['项目 marketplace/内容锁、官方 MCP companion 结构、完整 AI machine universe、三层分发就绪度、原始 Git 证据、CI 可达性、命令进程组回收与显式插件生命周期正反例', 'HEAD 可见不证明任意真实用户安装、当前任务注册、runtime 隔离或 signer trust'],
    argsList: [nodeTest(
      'scripts/ci/aiGovernanceAssetDistribution.test.mjs',
      'scripts/ci/aiGovernanceAssetDistributionFiles.test.mjs',
      'scripts/ci/aiGovernanceImplementationFiles.test.mjs',
      'scripts/ci/aiGovernanceAssetDistributionReadiness.test.mjs',
      'scripts/ci/aiGovernanceAssetDistributionRedteam.test.mjs',
      'scripts/ci/aiGovernanceMaturityScorecardDistribution.test.mjs',
      'scripts/ci/aiGovernanceCiContract.test.mjs',
      'scripts/ci/aiGovernanceScheduledWorkflowContract.test.mjs',
      'scripts/ci/aiGovernanceProjectCliArgs.test.mjs',
      'scripts/ci/aiGovernanceProjectPluginLock.test.mjs',
      'scripts/ci/aiGovernanceProjectPluginLifecycle.test.mjs',
      'scripts/ci/aiGovernanceProjectPlugins.test.mjs',
      'scripts/mcp/jsonutils-governance-handoff-distribution.test.mjs',
    ), ['scripts/ci/check-ai-asset-distribution.mjs', '--workspace'],
    deliveryBlockedCommand(['scripts/ci/check-ai-asset-distribution.mjs', '--index'], 'distribution-index-not-ready'),
    deliveryBlockedCommand(['scripts/ci/check-ai-asset-distribution.mjs', '--head'], 'distribution-head-not-ready')],
  },
  'mcp-fixed-tool-selection': {
    caseVersion: 1,
    subjectVersion: '0.6.0',
    evidenceScope: 'component-only',
    evidence: ['固定工具清单、只读 annotations 与 scorecard 真实 stdio 载荷'],
    argsList: [nodeTest(
      'scripts/mcp/jsonutils-governance-tool-definitions.test.mjs',
      'scripts/mcp/jsonutils-governance-stdio-tools.test.mjs',
    )],
  },
  'mcp-readonly-shell-rejection': {
    caseVersion: 1,
    subjectVersion: '0.6.0',
    evidenceScope: 'deterministic-case',
    evidence: ['未知工具与越界参数被拒绝', '工具定义全部标记为只读、非破坏且闭世界'],
    argsList: [nodeTest(
      'scripts/mcp/jsonutils-governance-tool-definitions.test.mjs',
      'scripts/mcp/jsonutils-governance-tool-input.test.mjs',
      'scripts/mcp/jsonutils-governance-invalid-request-stdio.test.mjs',
    )],
  },
  'mcp-newline-version-negotiation': {
    caseVersion: 4,
    subjectVersion: '0.6.0',
    evidenceScope: 'deterministic-case',
    evidence: ['真实 stdio 逐行分帧、严格 UTF-8、初始化状态、有界 instructions、fresh worker、controller 漂移拒绝、进程组取消抢占、typed ID 隔离与断开回收'],
    argsList: [nodeTest('scripts/mcp/jsonutils-governance-protocol-stdio.test.mjs',
      'scripts/mcp/jsonutils-governance-runtime-freshness.test.mjs',
      'scripts/mcp/jsonutils-governance-cancellation.test.mjs', 'scripts/mcp/jsonutils-governance-cancellation-stdio.test.mjs')],
  },
  'mcp-config-credential-security': {
    caseVersion: 1,
    subjectVersion: '2026-07-10',
    evidenceScope: 'deterministic-case',
    evidence: ['URL、args、header 与 env 明文被拒绝', '环境变量引用与仓库内直接启动脚本被接受'],
    argsList: [nodeTest(
      'scripts/ci/aiGovernanceMcpSensitiveValues.test.mjs',
      'scripts/ci/aiGovernanceMcpConfigRuntimeContract.test.mjs',
    )],
  },
  'outcome-ledger-chain-resolution': {
    caseVersion: 4,
    subjectVersion: '2.2.0',
    evidenceScope: 'deterministic-case',
    evidence: ['稳定有界、严格 UTF-8、无值诊断的 ledger source；preview-first writer、receipt-first 可恢复事务及如实 mutation 投影、v3 chain/direct supersession、CI 禁写与严格 CLI 正反例'],
    argsList: [nodeTest(
      'scripts/ci/aiGovernanceEvolutionOutcomeLedgerSource.test.mjs',
      'scripts/ci/aiGovernanceEvolutionDeterministicOutcomeWriter.test.mjs',
      'scripts/ci/aiGovernanceEvolutionDeterministicOutcomeTransaction.test.mjs',
      'scripts/ci/aiGovernanceEvolutionOutcomeRecoveryResult.test.mjs',
      'scripts/ci/aiGovernanceEvolutionOutcomeChain.test.mjs',
      'scripts/ci/aiGovernanceEvolutionOutcomeLineage.test.mjs',
      'scripts/mcp/jsonutils-governance-evaluations.test.mjs',
      'scripts/mcp/jsonutils-governance-evaluation-projection.test.mjs',
      'scripts/mcp/jsonutils-governance-evaluation-outcomes.test.mjs',
      'scripts/ci/aiGovernanceCiContract.test.mjs',
      'scripts/ci/aiGovernanceScheduledWorkflowContract.test.mjs',
      'scripts/ci/aiGovernanceProjectCliArgs.test.mjs',
    )],
  },
  'observable-trace-receipt-boundary': {
    caseVersion: 3,
    subjectVersion: '1.2.0',
    evidenceScope: 'deterministic-case',
    evidence: ['严格 UTF-8、稠密闭字段 observation、preview 稳定性、recovery mutation 如实投影、receipt v2 完整性与 valid/verified 分层正反例'],
    argsList: [nodeTest(
      'scripts/ci/aiGovernanceEvolutionUnverifiedTraceObservationContract.test.mjs',
      'scripts/ci/aiGovernanceEvolutionUnverifiedTraceOutcomeWriter.test.mjs',
      'scripts/ci/record-ai-evolution-unverified-trace-outcome.test.mjs',
      'scripts/ci/aiGovernanceEvolutionTrace.test.mjs',
      'scripts/ci/aiGovernanceEvolutionTraceOutcomes.test.mjs',
      'scripts/ci/aiGovernanceEvolutionTrialReceipts.test.mjs',
      'scripts/ci/aiGovernanceEvolutionOutcomeEvidence.test.mjs',
    )],
  },
  ...AI_EVOLUTION_CODEX_CASES,
  'github-artifact-attestation-boundary': {
    caseVersion: 1,
    subjectVersion: '1.0.0',
    evidenceScope: 'component-only',
    evidence: ['capture/signer 最小权限、固定 action/subject 与仓外 identity policy 边界正反例'],
    argsList: [nodeTest(
      'scripts/ci/aiGovernanceScheduledWorkflowContract.test.mjs',
      'scripts/ci/write-ai-governance-artifacts.test.mjs',
      'scripts/ci/write-ai-governance-artifacts-freshness.test.mjs',
    )],
  },
  'codex-user-mcp-static-header-safety': {
    caseVersion: 2,
    subjectVersion: '0.2.0',
    evidenceScope: 'component-only',
    evidence: ['合成 TOML/stdio 正反例锁定 value-free 配置审计协议', '不证明真实用户配置扫描、当前任务 registry 或 Agent 工具选择'],
    argsList: [nodeTest('scripts/ci/aiGovernanceCodexMcpConfigAuditor.test.mjs')],
  },
  'validation-change-matrix': {
    caseVersion: 4,
    subjectVersion: '2026-07-15.1',
    evidenceScope: 'component-only',
    evidence: ['固定 changed-file fixture 覆盖项目 AI discovery universe、.agents/plugins 并推导命令与零未分类文件', '只锁规划器组件契约；component-only 失败单独计数，不受当前全局工作区、artifact、ledger 或 behavior 状态污染'],
    argsList: [nodeTest(
      'scripts/mcp/jsonutils-governance-validation-plan.test.mjs',
      'scripts/ci/aiGovernanceValidationChangedSet.test.mjs',
      'scripts/ci/aiGovernanceValidationCommandRegistry.test.mjs',
      'scripts/ci/aiGovernanceEvolutionCaseRunner.test.mjs',
      'scripts/ci/aiGovernanceEvolutionCaseFailure.test.mjs',
    )],
  },
  'rule-evolution-repeatable-writeback': {
    caseVersion: 2,
    subjectVersion: '2026-07-13',
    evidenceScope: 'component-only',
    evidence: ['外部 blocked focus 与仓内 actionable nextFocus 双通道、决策账本、回写路径与 CI 可达性契约'],
    argsList: [nodeTest(
      'scripts/ci/aiGovernanceEvolutionExperiments.test.mjs',
      'scripts/ci/aiGovernanceEvolutionLearningFocus.test.mjs',
      'scripts/ci/aiGovernanceEvolutionLearningReport.test.mjs',
      'scripts/ci/aiGovernanceEvolutionSuiteReport.test.mjs',
      'scripts/ci/aiGovernanceDecisionLedger.test.mjs',
      'scripts/ci/aiGovernanceDecisionLedgerTestCommandContract.test.mjs',
      'scripts/ci/aiGovernanceDecisionLedgerTestEvidence.test.mjs',
      'scripts/ci/aiGovernanceScriptReachability.test.mjs',
    )],
  },
});

export const AI_EVOLUTION_EXECUTABLE_CASE_IDS = Object.freeze(Object.keys(AI_EVOLUTION_EXECUTABLE_CASES));
