const lines = values => values.join('\n');

export const AI_GOVERNANCE_REFERENCE_ENTRY_MISSING_CASES = [
  {
    name: 'AI 治理引用检查会报告入口文档缺失治理命令',
    file: 'AGENTS.md',
    content: lines(['rules/code-style.md', 'docs/AI-ENGINEERING-PLAYBOOK.md', '复盘沉淀', '规则/skill 回写', '治理校验']),
    contains: ['rules/code-style.md', 'docs/AI-ENGINEERING-PLAYBOOK.md', 'node scripts/ci/check-ai-governance.mjs'],
    expected: 'AGENTS.md: 缺少 "node scripts/ci/check-ai-governance.mjs"',
  },
  {
    name: 'AI 治理引用检查会报告入口文档缺失版本闭环文件',
    file: 'CLAUDE.md',
    content: lines([
      'rules/code-style.md',
      'docs/AI-ENGINEERING-PLAYBOOK.md',
      'node scripts/ci/check-ai-governance.mjs',
      'node scripts/ci/check-version-consistency.mjs',
      'frontend/package.json',
      'CHANGELOG.md',
    ]),
    contains: ['node scripts/ci/check-version-consistency.mjs', 'frontend/package.json', 'frontend/package-lock.json', 'CHANGELOG.md'],
    expected: 'CLAUDE.md: 缺少 "frontend/package-lock.json"',
  },
  {
    name: 'AI 治理引用检查会报告 Claude 目录 README 缺失治理入口',
    file: '.claude/README.md',
    content: lines(['AGENTS.md', 'CLAUDE.md', 'rules/code-style.md', '.claude/ai-tools-guide.md', 'node scripts/ci/check-ai-governance.mjs']),
    contains: ['AGENTS.md', 'CLAUDE.md', 'rules/code-style.md', 'docs/AI-ENGINEERING-PLAYBOOK.md', '.claude/ai-tools-guide.md', 'node scripts/ci/check-ai-governance.mjs'],
    expected: '.claude/README.md: 缺少 "docs/AI-ENGINEERING-PLAYBOOK.md"',
  },
  {
    name: 'AI 治理引用检查会报告 Cursor 入口缺失 Comate 同源入口',
    file: '.cursorrules',
    content: lines(['AGENTS.md', 'CLAUDE.md', 'rules/code-style.md', 'docs/AI-ENGINEERING-PLAYBOOK.md', 'node scripts/ci/check-ai-governance.mjs']),
    contains: ['.comate/rules/code-style.md'],
    expected: '.cursorrules: 缺少 ".comate/rules/code-style.md"',
  },
  {
    name: 'AI 治理引用检查会报告 Comate 入口缺失版本锁文件',
    file: '.comate/rules/code-style.md',
    content: lines(['frontend/package.json', 'CHANGELOG.md', 'node scripts/ci/check-version-consistency.mjs']),
    contains: ['frontend/package.json', 'frontend/package-lock.json', 'CHANGELOG.md'],
    expected: '.comate/rules/code-style.md: 缺少 "frontend/package-lock.json"',
  },
  {
    name: 'AI 治理引用检查会报告 PR 模板缺失决策账本追踪',
    file: '.github/PULL_REQUEST_TEMPLATE.md',
    content: lines(['docs/AI-ASSET-REGISTRY.md', 'node scripts/ci/check-ai-governance.mjs', '负向测试', '显式豁免', 'CHANGELOG.md']),
    contains: ['docs/AI-GOVERNANCE-DECISIONS.md'],
    expected: '.github/PULL_REQUEST_TEMPLATE.md: 缺少 "docs/AI-GOVERNANCE-DECISIONS.md"',
  },
  {
    name: 'AI 治理引用检查会报告 PR 模板缺失 Copilot 根入口',
    file: '.github/PULL_REQUEST_TEMPLATE.md',
    content: lines(['docs/AI-ASSET-REGISTRY.md', 'docs/AI-GOVERNANCE-DECISIONS.md', 'CHANGELOG.md', 'node scripts/ci/check-ai-governance.mjs', '.cursor/rules', '.github/instructions', '.github/prompts', '.github/agents', '.github/chatmodes', '负向测试', '显式豁免']),
    contains: ['.github/copilot-instructions.md', '.cursor/rules', '.github/instructions', '.github/prompts', '.github/agents', '.github/chatmodes'],
    expected: '.github/PULL_REQUEST_TEMPLATE.md: 缺少 ".github/copilot-instructions.md"',
  },
  {
    name: 'AI 治理引用检查会报告 PR 模板缺失预算提醒',
    file: '.github/PULL_REQUEST_TEMPLATE.md',
    content: lines(['docs/AI-ASSET-REGISTRY.md', 'docs/AI-GOVERNANCE-DECISIONS.md', 'CHANGELOG.md', 'node scripts/ci/check-ai-governance.mjs', '可维护性预算', '负向测试', '显式豁免']),
    contains: ['node scripts/ci/check-maintainability-budgets.mjs'],
    expected: '.github/PULL_REQUEST_TEMPLATE.md: 缺少 "node scripts/ci/check-maintainability-budgets.mjs"',
  },
  {
    name: 'AI 治理引用检查会报告 PR 模板缺失 MCP 配置提醒',
    file: '.github/PULL_REQUEST_TEMPLATE.md',
    content: lines(['docs/AI-ASSET-REGISTRY.md', 'docs/AI-GOVERNANCE-DECISIONS.md', 'CHANGELOG.md', 'node scripts/ci/check-ai-governance.mjs', '.cursor/mcp.json', '.vscode/mcp.json', '负向测试', '显式豁免']),
    contains: ['.mcp.json', '.cursor/mcp.json', '.vscode/mcp.json'],
    expected: '.github/PULL_REQUEST_TEMPLATE.md: 缺少 ".mcp.json"',
  },
  {
    name: 'AI 治理引用检查会报告配置分层说明缺失决策账本',
    file: 'docs/AI-CONFIG-INTEGRATION.md',
    content: lines(['rules/code-style.md', 'docs/AI-ENGINEERING-PLAYBOOK.md', 'docs/AI-ASSET-REGISTRY.md', '显式豁免']),
    contains: ['docs/AI-GOVERNANCE-DECISIONS.md'],
    expected: 'docs/AI-CONFIG-INTEGRATION.md: 缺少 "docs/AI-GOVERNANCE-DECISIONS.md"',
  },
  {
    name: 'AI 治理引用检查会报告配置分层说明缺失 Copilot 根入口',
    file: 'docs/AI-CONFIG-INTEGRATION.md',
    content: lines(['rules/code-style.md', 'docs/AI-ENGINEERING-PLAYBOOK.md', 'docs/AI-ASSET-REGISTRY.md', 'docs/AI-GOVERNANCE-DECISIONS.md', '.cursor/rules', '显式豁免']),
    contains: ['.github/copilot-instructions.md'],
    expected: 'docs/AI-CONFIG-INTEGRATION.md: 缺少 ".github/copilot-instructions.md"',
  },
  {
    name: 'AI 治理引用检查会报告工具索引缺失决策账本',
    file: 'docs/AI-TOOLS-SETUP.md',
    content: lines(['docs/AI-CONFIG-INTEGRATION.md', 'docs/AI-ASSET-REGISTRY.md', 'node scripts/ci/check-ai-governance.mjs']),
    contains: ['docs/AI-GOVERNANCE-DECISIONS.md'],
    expected: 'docs/AI-TOOLS-SETUP.md: 缺少 "docs/AI-GOVERNANCE-DECISIONS.md"',
  },
  {
    name: 'AI 治理引用检查会报告资产注册表缺失 Copilot 根入口人审契约',
    file: 'docs/AI-ASSET-REGISTRY.md',
    content: lines(['AGENTS.md', 'CLAUDE.md', 'docs/AI-ENGINEERING-PLAYBOOK.md', 'docs/AI-GOVERNANCE-DECISIONS.md', '.codex/skills/jsonutils-maintainer/SKILL.md', 'scripts/ci/check-ai-governance.mjs', 'scripts/ci/aiGovernanceAssetRegistryEvidence.mjs', 'referenceRules.file', '治理证据', '显式豁免']),
    contains: ['Copilot 根入口'],
    expected: 'docs/AI-ASSET-REGISTRY.md: 缺少 "Copilot 根入口"',
  },
];
