export const staticRetentionEntrypointFile = 'frontend/docker-entrypoint.d/40-sync-static-assets.sh';

export const requiredStaticRetentionSnippets = [
  { file: 'frontend/Dockerfile', snippets: [
    'COPY --from=build /app/dist /opt/jsonutils-dist',
    'COPY docker-entrypoint.d/40-sync-static-assets.sh /docker-entrypoint.d/40-sync-static-assets.sh',
    'RUN chmod +x /docker-entrypoint.d/40-sync-static-assets.sh',
  ] },
  { file: 'frontend/Dockerfile.prebuilt', snippets: [
    'COPY dist /opt/jsonutils-dist',
    'COPY docker-entrypoint.d/40-sync-static-assets.sh /docker-entrypoint.d/40-sync-static-assets.sh',
    'RUN chmod +x /docker-entrypoint.d/40-sync-static-assets.sh',
  ] },
  { file: 'docker-compose.yml', snippets: [
    'STATIC_ASSET_RETENTION_DAYS=${STATIC_ASSET_RETENTION_DAYS:-14}',
    'frontend-static:/usr/share/nginx/html',
    'frontend-static:',
  ] },
  { file: 'docker-compose.local.yml', snippets: [
    'STATIC_ASSET_RETENTION_DAYS=${STATIC_ASSET_RETENTION_DAYS:-14}',
    'frontend-static:/usr/share/nginx/html',
    'frontend-static:',
  ] },
  { file: 'scripts/deploy/frontend-legacy-assets.sh', snippets: [
    'FRONTEND_LEGACY_ASSET_RETENTION_ENABLED',
    'compose cp "$service:$static_root/assets/."',
    'compose cp "$FRONTEND_LEGACY_ASSET_BACKUP_DIR/assets/."',
  ] },
  { file: 'scripts/deploy/remote-docker-compose-deploy.sh', snippets: [
    '. "$APP_DIR/scripts/deploy/frontend-legacy-assets.sh"',
    'trap cleanup_frontend_legacy_assets EXIT',
    'backup_frontend_legacy_assets',
    'restore_frontend_legacy_assets',
  ] },
  { file: 'scripts/deploy/ssh-docker-compose-deploy.sh', snippets: [
    'DEFAULT_PUBLIC_BASE_URL="${DEFAULT_PUBLIC_BASE_URL:-https://jsonutils.markz.fun}"',
    'PUBLIC_VERIFY_INSECURE_TLS="${PUBLIC_VERIFY_INSECURE_TLS:-false}"',
    'PUBLIC_FRONTEND_ASSET_VERIFY_INSECURE_TLS="${PUBLIC_FRONTEND_ASSET_VERIFY_INSECURE_TLS:-$PUBLIC_VERIFY_INSECURE_TLS}"',
    'local public_base_url="${PUBLIC_BASE_URL:-$DEFAULT_PUBLIC_BASE_URL}"',
    'local legacy_assets_file',
    'local legacy_capture_status=0',
    'node "$ROOT_DIR/scripts/ci/check-production-frontend-assets.mjs" "$public_base_url" --print-paths',
    'legacy_capture_status=$?',
    '部署前公网前端静态资源捕获失败，且未产出任何旧资源路径',
    'PUBLIC_BASE_URL="${PUBLIC_BASE_URL:-$DEFAULT_PUBLIC_BASE_URL}"',
  ] },
  { file: 'scripts/deploy/verify-public-deploy.sh', snippets: [
    'DEFAULT_PUBLIC_BASE_URL="${DEFAULT_PUBLIC_BASE_URL:-https://jsonutils.markz.fun}"',
    'PUBLIC_BASE_URL="${PUBLIC_BASE_URL:-$DEFAULT_PUBLIC_BASE_URL}"',
    'PUBLIC_VERIFY_INSECURE_TLS="${PUBLIC_VERIFY_INSECURE_TLS:-false}"',
    'PUBLIC_FRONTEND_ASSET_VERIFY_INSECURE_TLS="${PUBLIC_FRONTEND_ASSET_VERIFY_INSECURE_TLS:-$PUBLIC_VERIFY_INSECURE_TLS}"',
    'CURL_TLS_ARG=""',
  ] },
  { file: '.github/workflows/ci.yml', snippets: [
    'run: node scripts/ci/check-maintainability-budgets.mjs',
    'run: node --test scripts/ci/*.test.mjs',
    'run: node scripts/ci/check-frontend-static-retention.mjs',
    'run: node scripts/ci/check-ai-governance.mjs',
  ] },
  { file: '.github/workflows/deploy.yml', snippets: [
    'public_verify_insecure_tls:',
    "DEFAULT_PUBLIC_BASE_URL: 'https://jsonutils.markz.fun'",
    'run: node scripts/ci/check-frontend-static-retention.mjs',
    'legacy_assets_file="$(mktemp)"',
    'legacy_capture_status=0',
    'node scripts/ci/check-production-frontend-assets.mjs "$base_url" --print-paths',
    'legacy_capture_status=$?',
    'Failed to capture legacy frontend assets and no asset paths were produced.',
    'printf \'LEGACY_FRONTEND_ASSETS=%s\\n\' "$legacy_assets" >> "$GITHUB_ENV"',
    'FRONTEND_ASSET_VERIFY_EXTRA_PATHS: ${{ env.LEGACY_FRONTEND_ASSETS }}',
    'PUBLIC_FRONTEND_ASSET_VERIFY_ENABLED: \'true\'',
    'PUBLIC_FRONTEND_ASSET_VERIFY_INSECURE_TLS: ${{ inputs.public_verify_insecure_tls }}',
    'PUBLIC_VERIFY_INSECURE_TLS: ${{ inputs.public_verify_insecure_tls }}',
    'base_url="${PUBLIC_BASE_URL:-$DEFAULT_PUBLIC_BASE_URL}"',
    'run: bash scripts/deploy/verify-public-deploy.sh',
  ] },
];
