spring:
  application:
    name: json-helper-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/jsonhelper
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration

  # 文件上传大小限制
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

server:
  port: 8080

# 文件上传目录配置
file:
  upload-dir: ./uploads

# JWT Configuration
jwt:
  secret: D+d8lKHErzwkqdz29GvxwV/O3SEw6uMvdNk181jFfP8NQDSN4R0iWNAjI5h/Lazf9SnPULCNU83s73yfMxbTZg==
  expiration: 86400000 # 1 day
